// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Colors are 32-bit ARGB values, as returned by `Color.toARGB32()`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ThemeMessage: Hashable, CustomStringConvertible {
  var actionLight: Int64? = nil
  var actionDark: Int64? = nil
  var titleLight: Int64? = nil
  var titleDark: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThemeMessage? {
    let actionLight: Int64? = nilOrValue(pigeonVar_list[0])
    let actionDark: Int64? = nilOrValue(pigeonVar_list[1])
    let titleLight: Int64? = nilOrValue(pigeonVar_list[2])
    let titleDark: Int64? = nilOrValue(pigeonVar_list[3])

    return ThemeMessage(
      actionLight: actionLight,
      actionDark: actionDark,
      titleLight: titleLight,
      titleDark: titleDark
    )
  }
  func toList() -> [Any?] {
    return [
      actionLight,
      actionDark,
      titleLight,
      titleDark,
    ]
  }
  static func == (lhs: ThemeMessage, rhs: ThemeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.actionLight, rhs.actionLight) && MessagesPigeonInternal.deepEquals(lhs.actionDark, rhs.actionDark) && MessagesPigeonInternal.deepEquals(lhs.titleLight, rhs.titleLight) && MessagesPigeonInternal.deepEquals(lhs.titleDark, rhs.titleDark)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThemeMessage")
    MessagesPigeonInternal.deepHash(value: actionLight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: actionDark, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: titleLight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: titleDark, hasher: &hasher)
  }

  public var description: String {
    return "ThemeMessage(actionLight: \(String(describing: actionLight)), actionDark: \(String(describing: actionDark)), titleLight: \(String(describing: titleLight)), titleDark: \(String(describing: titleDark)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ThemeMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ThemeMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ParakeyHostApi {
  func configure(tokenBundle: String) async throws
  func deconfigure() async throws
  func showScan() async throws
  func unlock(deviceId: String) async throws
  func setTheme(theme: ThemeMessage) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ParakeyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ParakeyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ParakeyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.parakey_sdk_flutter.ParakeyHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenBundleArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.configure(tokenBundle: tokenBundleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let deconfigureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.parakey_sdk_flutter.ParakeyHostApi.deconfigure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deconfigureChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.deconfigure()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      deconfigureChannel.setMessageHandler(nil)
    }
    let showScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.parakey_sdk_flutter.ParakeyHostApi.showScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showScanChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.showScan()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      showScanChannel.setMessageHandler(nil)
    }
    let unlockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.parakey_sdk_flutter.ParakeyHostApi.unlock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unlockChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.unlock(deviceId: deviceIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      unlockChannel.setMessageHandler(nil)
    }
    let setThemeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.parakey_sdk_flutter.ParakeyHostApi.setTheme\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setThemeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let themeArg = args[0] as! ThemeMessage
        do {
          try api.setTheme(theme: themeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setThemeChannel.setMessageHandler(nil)
    }
  }
}
